### ISSUE TITLE
Links are not working on  Safari

### ISSUE THREAD

**Issue by ICTServ** [vendure-ecommerce/storefront-qwik-starter#106]
Even I tried on official demo site https://qwik-storefront.vendure.io and all links are not working. I use safari V14. 

ReferenceError: Can't find variable: SubmitEvent

**Comment by gioboa** [comment]
Thanks for the feedback, I will investigate on that

**Comment by gioboa** [comment]
@ICTServ which version of safari are you using ?

**Comment by gioboa** [comment]
@prasmalla have you got the possibility to test the app with safari 14?

**Comment by michaelbromley** [comment]
I have a Browserstack account and just tested it on Safari v14.1 and can confirm that navigation does not work.

On loading the landing page, the following error appears in the console:

![image](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/6275952/158579e8-e20e-4943-9781-2240817e255e)

Clicking the `...85b.js` file at the top of the stack trace leads to this: 
![image](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/6275952/5c90ddcc-45c4-417c-90f6-bd2db9eb0e70)

**Comment by gioboa** [comment]
🤔 the initial error is different, so we have multiple errors with Safari v14 😅

**Comment by yasserlens** [comment]
Do you know if this is a qwik issue rather than this repo?

**Comment by gioboa** [comment]
You can try with a [Qwik fresh app](https://qwik.builder.io/docs/getting-started/#create-an-app-using-the-cli) and verify the behaviour

**Comment by gioboa** [comment]
Stale issue. I close it.
Ultimately this is a Qwik problem.
Thanks
