### ISSUE TITLE
Braintree plugin issue

### ISSUE THREAD

**Issue by msj121** [vendure-ecommerce/storefront-qwik-starter#113]
I have added the braintree plugin as suggested on vendure, and used it as a payment method from vendure admin.

I see a "pay with braintree" button on my front end, enter the credit card etc.. but when I hit the pay button I get the following:

```
Uncaught (in promise) TypeError: res is null
addPaymentToOrderMutation checkout.ts:28
```

checkout.ts 28:44 -->

```
export const addPaymentToOrderMutation = async (
	input: PaymentInput = { method: 'standard-payment', metadata: {} }
) => {
	return sdk
		.addPaymentToOrder({ input })
		.then((res: AddPaymentToOrderMutation) => res.addPaymentToOrder as Order); <--- line 28
};
```
Any thoughts? I definitely have the braintree plugin setup and have synchronized the vendure database... so I assume this is an issue here? Also checked my generated folder and graphql matches latest - I only setup this project maybe a week or so ago. Happy to test anything else out

Noted on Vendure Server:

```
1|vendure  | [server] warn 7/14/23, 9:48 PM - [Vendure Server] The orderId argument to the generateBraintreeClientToken mutation has been deprecated and may be omitted. 
1|vendure  | [server] warn 7/14/23, 9:48 PM - [Vendure Server] USER_INPUT_ERROR: error.payment-method-not-found
```

**Comment by gioboa** [comment]
@prasmalla you are the man for this issue. Thanks in advance 🙂

**Comment by prasmalla** [comment]
as the error shows USER_INPUT_ERROR payment method not found on the server. pls make sure you named the payment method with 'Braintree Payment'

**Comment by msj121** [comment]
Thank you so much! 

After looking at the BraintreePayment.tsx I now see the "method" which didn't click needed to be the "code" for the payment. Makes obvious sense now.

For others following this issue: I needed to delete my payment method from the admin and remake it, not just change the code. Only changing the code and name, got me a different error even after restarting the server. Maybe it was just me, but heads up.
