### ISSUE TITLE
sticky header not working

### ISSUE THREAD

**Issue by msj121** [vendure-ecommerce/storefront-qwik-starter#118]
Header does not stick when scrolling, even though I see tailwind css for it. Trying to find the bug, usually overflow, but I can't find it.

Other stores are also having this issue (remix/angular - although theirs are a little more buggy).

**Comment by gioboa** [comment]
Can you attach a gif to show the problem pls?

**Comment by msj121** [comment]
@gioboa Sure, the issue also applies to default store. Top image you can see the main load screen with bar at top

<img width="1382" alt="Screen Shot 2023-07-19 at 3 16 31 PM" src="https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/6738227/71fab260-7ac1-4c29-a393-70d88fd6c6db">

Here you can see as you scroll there is no header that sticks, I can see the tailwind class for sticky, but it is not working.
<img width="1385" alt="Screen Shot 2023-07-19 at 3 16 46 PM" src="https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/6738227/ace4a5fc-448b-4c4b-8e4f-5fad10ed3fda">

**Comment by gioboa** [comment]
I see, thanks for the feedback. I will investigate in it

**Comment by msj121** [comment]
Hmm, nvm that messes up the cart anyway lol.

**Comment by msj121** [comment]
@gioboa Okay I made a PR where I did some quick checking it works. Not sure if design wise it is what you want but here is a snapshot below:

<img width="1325" alt="Screen Shot 2023-07-19 at 6 07 41 PM" src="https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/6738227/c02c0e75-0a3a-4fd4-a875-3c7378cc3a88">
