### ISSUE TITLE
Stripe doesn't work ?

### ISSUE THREAD

**Issue by Gunther-443** [vendure-ecommerce/storefront-qwik-starter#128]
Hello,

I can't get Stripe to work.
I have two SSL demo servers:

Vendure : 
- I added StripePlugin in vendure config.
- Create a new PaymentMethod in the Admin UI, and select "Stripe payments" as the handler.
- Set the webhook secret and API key in the PaymentMethod form.

storefront-qwik-starter :
- I have filled in VITE_STRIPE_PUBLISHABLE_KEY

When it's time to pay, I get this error :
Error: This API call cannot be made with a publishable API key. Please use a secret API key. You can find a list of your API keys at https://dashboard.stripe.com/account/apikeys.
**(I did fill in these fields in Vendure Admin UI)**

I don't understand a word ...
Does anyone have any ideas?

Thanks

**Comment by prasmalla** [comment]
you use publishable key in storefront and need the secret key in vendure admin

**Comment by Gunther-443** [comment]
> you use publishable key in storefront and need the secret key in vendure admin

Yes

**Comment by prasmalla** [comment]
@Gunther-443 were you able to get it working and if so we can close this issue?

**Comment by gioboa** [comment]
Stale issue. I close it, thanks
