### ISSUE TITLE
83 point Best practise Lighthouse benchmark

### ISSUE THREAD

**Issue by TimKieu** [vendure-ecommerce/storefront-qwik-starter#129]
Deploy to CloudFlare Pages

qwik-insights.builde…2fwnm5u5bvt/post/:1 | Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
-- | --

PLease help, thanks much

**Comment by gioboa** [comment]
Hi, can you explain me the issue please?

**Comment by gioboa** [comment]
Stale issue. I close it, thanks
