### ISSUE TITLE
Thanks for sharing the repo

### ISSUE THREAD

**Issue by ashishkpaul** [vendure-ecommerce/storefront-qwik-starter#131]
Hello sir, although I am not a developer, I was able to install it on a VPS with a Node.js adapter by reading the instructions. It is really very fast, well-featured, and easy to install. I did not find any issues. However, I have three concerns:

1. The search bar is not showing on mobile.
2. Multiple product assets (images, videos) are not showing on storefront.
3. We are using Stripe to make a payment from the storefront, the screen does not automatically scroll to the payment gateway applet. The user has to scroll up the page to view the payment gateway.

**Comment by gioboa** [comment]
Hi, I am so glad you like the app.
Please open separate feature request for these tasks. 😉 I'm closing this issue, I am so happy to improve the application with other features. Thanks
