### ISSUE TITLE
feat: image preview + mobile searchBar + stripe

### ISSUE THREAD

**Issue by ashishkpaul** [vendure-ecommerce/storefront-qwik-starter#132]
Please accept and mark as with a lable of enhancement .
1. The search bar is not showing on mobile.
2. Multiple product assets (images, videos) are not showing on storefront.
3. We are using Stripe to make a payment from the storefront, the screen does not automatically scroll to the payment gateway applet. The user has to scroll up the page to view the payment gateway and same for user sign-up page  (you can add the notification at bottom of the sign-up page "Account registration is not supported by the demo Vendure instance. In order to use it, please connect to your own local / production instance.")

**Comment by gioboa** [comment]
Do you have any mockup for the point 1 and 2?
I really would like to implement these features.
For the stripe case I will ping @prasmalla 🚀

**Comment by ashishkpaul** [comment]
Point 1. snapshot (No search bar in mobile)
![Screenshot_2023-09-20_21-53-18](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/16308863/d8b0c98b-2fbb-4043-93e5-a3dc8ff06986)
Point 2. Multiple product assets (images, videos) are not showing on storefront.
![Presentation_Ashish Khetarpal's Room_2023-09-20T16_42_03 328Z](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/16308863/0bd86566-d224-44b2-8131-b4a746b34db5)

**Comment by gioboa** [comment]
Yep, I see. Do you have any design for them? I'll implement these features based on your requirements

**Comment by ashishkpaul** [comment]
Drafting 
Front view
![Presentation_Ashish Khetarpal's Room_2023-09-21T11_25_14 149Z](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/16308863/70c138a3-83fe-4a8a-a484-49444473d1a4)
Product Detail page
![Presentation_Ashish Khetarpal's Room_2023-09-21T11_32_35 540Z](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/16308863/d5b8f99c-0353-4e2f-b1d3-3b0e333862cb)

**Comment by gioboa** [comment]
Thanks.
I will work on the multi images task first

**Comment by gioboa** [comment]
I will create another issue for the search bar

**Comment by ashishkpaul** [comment]
> I will create another issue for the search bar

I am glad to see that multiple assets are now showing. Thank you for your assistance, time and efforts.
