### ISSUE TITLE
how to up second storefront

### ISSUE THREAD

**Issue by ashishkpaul** [vendure-ecommerce/storefront-qwik-starter#133]
Hello sir, How we can up second Qwik Storefront in a  multi-vendor plugin or multi tenant setup, i added the VITE_VENDURE_LOCAL_URL=http://localhost:3000/shop-api?vendure-token=bobs-parts-token but its picking default channel

**Comment by gioboa** [comment]
@michaelbromley do you have any suggestion for this scenario? Thanks in advance 💪

**Comment by michaelbromley** [comment]
@ashishkpaul you need to pass the channel token as a header, not a query string.

**Comment by gioboa** [comment]
Thanks @michaelbromley 🚀
