### ISSUE TITLE
Accessing undefined in routes/layouts.tsx

### ISSUE THREAD

**Issue by anthonygregis** [vendure-ecommerce/storefront-qwik-starter#141]
**Issue**
There is a crashing error in the layout when setting up the AppStore state for a fresh vendure deployment. If there is no list of available country codes the following check still passes as a truthy value is passed, so it ends up accessing a non existent 0 index. Instead should check values is defined and check that length is `> 0`.

**Steps to reproduce**
1. Deploy vendure server / worker with no countries
2. Deploy qwik starter site pointed at fresh api
3. Try to access qwik starter site and see error

**Proposed Resolution**
Add an additional check to ensure that the array is not empty before trying to access the first item.

**Reference**
[src/routes/layout.tsx (Line 63)](https://github.com/vendure-ecommerce/storefront-qwik-starter/blob/c1b18d9a583388a8e2c019037465c315c10f5aae/src/routes/layout.tsx#L63)

**Comment by michaelbromley** [comment]
Hi, thanks for the report! Would you be interested in submitting a pull request to fix this?

**Comment by gioboa** [comment]
Thanks @anthonygregis 👍
