### ISSUE TITLE
feat: cash on delivery

### ISSUE THREAD

**Issue by ilovethensa** [vendure-ecommerce/storefront-qwik-starter#144]
Is there a way for people to make orders, and only pay when we deliver it to them? i dont really trust myself to handle credit cards i would rather people make orders and pay the delivery man

**Comment by ashishkpaul** [comment]
cash on delivery (cod) just configure dummy payemnt method on vendure core side.

**Comment by gioboa** [comment]
Thanks @ashishkpaul 
are you using this kind of payment?

**Comment by ashishkpaul** [comment]
![Presentation_Ashish Khetarpal's Room_2023-12-07T04_08_36 113Z](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/16308863/218d4022-513c-428c-9042-5024b627fc43)
![Presentation_Ashish Khetarpal's Room_2023-12-07T04_02_15 263Z](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/16308863/d6120d38-6788-46f3-a397-3c15596639ce)
![Presentation_Ashish Khetarpal's Room_2023-12-07T04_05_27 673Z](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/16308863/4ee42ec8-06d3-4139-aadf-27056be53f6e)

**Comment by gioboa** [comment]
Thanks @ashishkpaul.
@ashishkpaul I'm closing this issue for now, feel free to re-open it if it's still an issue for you.
