### ISSUE TITLE
Updated README.md and installation instructions to reflect the use of pnpm install

### ISSUE THREAD

**Issue by NoahPerez** [vendure-ecommerce/storefront-qwik-starter#149]
Problem:
When attempting to run the project using npm run dev, I encountered an error due to incorrect dependency installation. The project was initially set up with npm install, but this did not properly install the dependencies.

Solution:
To resolve this issue, I propose using pnpm install instead of npm install for dependency installation. Additionally, the project should be run using pnpm run dev to ensure compatibility with the dependency management approach.

Implementation Details:

Updated README.md and installation instructions to reflect the use of pnpm install.
Modified package.json scripts to use pnpm commands (pnpm run dev).
Tested the solution by running the project with pnpm install and pnpm run dev to ensure correct functionality.

Benefits:

Using PNPM offers improved performance and reduced disk space usage compared to other package managers.
Ensures consistent dependency installation across different environments.

**Comment by gioboa** [comment]
Thanks @NoahPerez, can you drop a PR to solve this issue pls? Thanks

**Comment by kitesurf** [comment]
I had the same problems:
The installation with npm and yarn cancelled with different error messages.
The only thing that worked was an installation with pnpm, and then of course a 
pnpm run dev
My Versions:
Mac with Monterey 12.7.1
Node 20.10.0
npm 10.2.3
yarn 1.22.19
and the good one
pnpm 8.15.1

**Comment by gioboa** [comment]
I see. In fact, `pnpm` is the official way to install the dependency in this project.

**Comment by kitesurf** [comment]
I am far from being able to contribute to this very good project via a pull request, but it would be very beneficial for other possible users if at least the "npm" commands were replaced in the readme by "pnpm" commands.
