### ISSUE TITLE
Failed to load @builder.io/qwik-labs dependency on startup

### ISSUE THREAD

**Issue by yohamta** [vendure-ecommerce/storefront-qwik-starter#160]
## Description
When starting the development server, an error occurs while loading the `@builder.io/qwik-labs` dependency. The error is displayed directly in the browser window, preventing the application from loading properly.

## Screenshot

<img width="1727" alt="image" src="https://github.com/user-attachments/assets/8bac8247-a30b-4a50-95b6-1f817a4cc058">

## Error Message
```
Failed to load url /node_modules/.pnpm/@builder.io+qwik-labs@[git+https+++git@github.com](mailto:git+https+++git@github.com)+BuilderIo+qwik-labs-build.git#36582dc0_i5v7r4c62lx7nepuxqskt7i55m/node_modules/@builder.io/qwik-labs/lib/index.qwik.mjs (resolved id: /path/to/the/repo/storefront-qwik-starter/node_modules/.pnpm/@builder.io+qwik-labs@[git+https+++git@github.com](mailto:git+https+++git@github.com)+BuilderIo+qwik-labs-build.git#36582dc0_i5v7r4c62lx7nepuxqskt7i55m/node_modules/@builder.io/qwik-labs/lib/index.qwik.mjs) in /path/to/the/repo/storefront-qwik-starter/src/components/head/head.tsx. Does the file exist?
```

## Steps to Reproduce
1. Clone the storefront-qwik-starter repository
2. Run `pnpm install`
3. Start the development server by running `pnpm start`
4. Open http://localhost:5173/ in a browser

## Environment
- OS: MacOS (Apple M2 Max)
- Node.js version: v22.4.1
- pnpm version: 9.1.2

## Additional Information
- I've tried cleaning and reinstalling node_modules
- The error persists even after updating to the latest version of the repository
- The file mentioned in the error message **exists** in the specified location

## Questions
1. Is this a known issue with the current version of `@builder.io/qwik-labs`?
2. Are there any specific version requirements for `@builder.io/qwik-labs` that I should be aware of?
3. Could this be related to how pnpm is resolving Git dependencies?

Any assistance in resolving this issue would be greatly appreciated. Thank you!

**Comment by gioboa** [comment]
Can you try with the latest version of Qwik packages please?

**Comment by friedger** [comment]
Not sure which versions to put. My trials fails, therefore I removed quik-labs.

It would be nice to have a working solution when cloning the repo.

**Comment by gioboa** [comment]
Let's remove qwik-labs. I'll create a PR for that

**Comment by gioboa** [comment]
Fixed by https://github.com/vendure-ecommerce/storefront-qwik-starter/commit/20f39871ce03ba008578413e587340908a21960c
