### ISSUE TITLE
Local Vendure API URL Not Recognized in Development Mode

### ISSUE THREAD

**Issue by yohamta** [vendure-ecommerce/storefront-qwik-starter#161]
**Description:**
I am trying to run the Vendure Qwik storefront locally and connect it to my local Vendure server. However, despite setting the environment variable for the API URL in the `.env` file, the application continues to connect to the demo API at `https://readonlydemo.vendure.io/shop-api`.

**Steps to Reproduce:**
1. Clone the repository: `git clone https://github.com/vendure-ecommerce/storefront-qwik-starter.git`
2. Navigate to the project directory: `cd storefront-qwik-starter`
3. Create a `.env` file with the following content:
```
VITE_IS_LOCAL=true
VITE_VENDURE_PUBLIC_URL=http://localhost:3000/shop-api
VITE_VENDURE_LOCAL_URL=http://localhost:3000/shop-api
VITE_VENDURE_API_URL=http://localhost:3000/shop-api
VITE_VENDURE_CHANNEL_TOKEN=default_channel
```
4. Run the development server: `npm run dev`
5. Observe that the application http://localhost:8080/ connects to the demo API instead of my local Vendure server.

**Expected Behavior:**
The application should connect to the local Vendure server as specified in the `.env` file.

**Actual Behavior:**
The application continues to connect to `https://readonlydemo.vendure.io/shop-api`.

**Additional Information:**
- I have verified that the `.env` file is in the root directory and correctly formatted.
- I have checked the `vite.config.ts` file to ensure it loads environment variables.
- I have restarted the development server after making changes.

**Environment:**
- Operating System: MacOS (M2 Max)
- Node.js version: v22.4.1
- npm version: 10.8.1

Please let me know if there are any additional steps I should take or if there is a known issue with environment variable handling in the current setup. Thank you!

**Comment by gioboa** [comment]
You did the right steps but at the moment the application is using [these constants](https://github.com/vendure-ecommerce/storefront-qwik-starter/blob/f4f085b1f1463e36306498c2dc3fc8f36fd8ccfb/src/constants.ts#L18)
We should switch and use the environment variables. A PR is more than welcome.
