### ISSUE TITLE
How to fix mixed content ?

### ISSUE THREAD

**Issue by loganess** [vendure-ecommerce/storefront-qwik-starter#165]
Hello,

I am using proxy for ssl termination and getting mixed contents issue, so all images can't be loaded.
There is no issue if accessing using internal ip.

Anyone has idea how to fix it.
Thank you.

**Comment by ashishkpaul** [comment]
On localhost or on a production server

**Comment by loganess** [comment]
on production server.

**Comment by ashishkpaul** [comment]
https://docs.vendure.io/reference/core-plugins/asset-server-plugin/asset-server-options#asseturlprefix

**Comment by ashishkpaul** [comment]
First check assetUrlPrefix: https://storefront-domain.lan

**Comment by loganess** [comment]
Great. I missed this.
Thanks a lot.
