### ISSUE TITLE
Displaying same price for all variants

### ISSUE THREAD

**Issue by ashishkpaul** [vendure-ecommerce/storefront-qwik-starter#169]
Fresh installed , On a product detail page, displaying same price for all variants of the products.
![Screenshot_2024-12-24_12-40-25](https://github.com/user-attachments/assets/3d4798ca-d48a-4631-a306-f00ec9280f6a)
But displaying correct price in a cart
![Screenshot_2024-12-24_12-45-38](https://github.com/user-attachments/assets/eed73829-17d8-4733-9d72-abf234487884)

**Comment by gioboa** [comment]
Hi, thanks for your feedback, is it something related to the latest update? ( Qwik v2 )
