### ISSUE TITLE
?langugeCode do not work with change in language , in search page 

### ISSUE THREAD

**Issue by shubhamchoudhary-2003** [vendure-ecommerce/storefront-qwik-starter#173]
hi going through search product gql it do not take the language instead it

**Comment by gioboa** [comment]
Thanks for the feedback, would you like to drop a PR to solve it? Thanks

**Comment by shubhamchoudhary-2003** [comment]
actually i am not been able to solvd it , can we have a discussion on this ?? who to get this with language

**Comment by gioboa** [comment]
Let's continue the discussion in the #104 one.
I close this because it's a duplicate.
Thanks
