### ISSUE TITLE
Add Alt attribute to Product Img tags

### ISSUE THREAD

**Issue by machineloop** [vendure-ecommerce/storefront-qwik-starter#19]
Add 'alt' attribute to `Img` tags. Maybe I need to add a name or description to [the GQL query](https://github.com/vendure-ecommerce/storefront-qwik-starter/blob/e6f026ec4852af62e66e49867d8d6eb7397c83cc/src/graphql/queries.ts) for [each Product](https://github.com/vendure-ecommerce/storefront-qwik-starter/blob/9082670b7f5e4387a1e301f981e668a4e5456035/src/types.ts) in the rendered collection? Then I can pull that product name/description and drop it in the alt attribute in the [CollectionCard](https://github.com/vendure-ecommerce/storefront-qwik-starter/blob/9082670b7f5e4387a1e301f981e668a4e5456035/src/components/collection-card/CollectionCard.tsx) component.

<img width="711" alt="Missing-Img-Alt-Attributes" src="https://user-images.githubusercontent.com/3682072/205055600-7070e8a0-eb67-408a-9cb9-abd14c3b3925.png">

From [MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names#content_with_images_must_be_labeled):

> [Content with images must be labeled](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names#content_with_images_must_be_labeled)
> 
> Provide descriptive text for all contentful (that is, non-decorative) images and image-like elements. This includes SVG images, [<img>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img), [<canvas>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas), [<map>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/map), and [<area>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area) elements, as well as [<input>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) elements where type=image and [<object>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object) elements where the type starts with image/. The typical way to do this is with the alt attribute. Be sure that the description conveys what is shown in the image.
> [Example](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Text_labels_and_names#example_4)
> 
> <img
>   src="milkweed.jgp"
>   alt="Black and white close-up photo of milkweed flowers" />

**Comment by michaelbromley** [comment]
Yes, using the product name as the alt text makes sense 👍
