### ISSUE TITLE
Use Link component for SPA navigation

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/storefront-qwik-starter#42]
Currrently internal navigations do full page reloads. Per Giorgio there was an issue with the Link component at some point - it needs to be checked in the latest Qwik City to see if we can implement SPA mode nav.

**Comment by gioboa** [comment]
Fixed with #50

**Comment by michaelbromley** [comment]
Great! You are wrapping up this issues qwikly! 😆 

One thing I just noticed is that the sub-collection cards don't quite work. They update the url but the actual view does not change
![image](https://user-images.githubusercontent.com/6275952/208930692-6467c7f7-12d7-4b97-9e04-dedc80338eda.png)

**Comment by gioboa** [comment]
I will open another issue for that. the search isn't working as well 😢
