### ISSUE TITLE
Cart quantity change not reflecting in UI

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/storefront-qwik-starter#43]
With an item in the cart, using the quantity adjustment does execute the correct mutation, but the new totals are not reflected in the UI.

![image](https://user-images.githubusercontent.com/6275952/208737576-d72c313e-5b6f-4cee-9194-407be0e2ac92.png)

**Comment by gioboa** [comment]
This commit [815881c](https://github.com/gioboa/storefront-qwik-starter/commit/815881cf83617da9f9fa114027fa13cd6512e516) fix the issue.
