### ISSUE TITLE
Re-work data layer to go via Qwik API route

### ISSUE THREAD

**Issue by michaelbromley** [vendure-ecommerce/storefront-qwik-starter#44]
Currently, direct GraphQL calls are being made from the client to the Vendure server. We should instead set up Qwik City API routes to handle these, so all calls to Vendure go via the server.

This will simplify session management and also allow us to server-render even client-specific data.

**Comment by gioboa** [comment]
Waiting for the new action$ API is a smart move because will save unnecessary rewriting

**Comment by gioboa** [comment]
Implemented with [this commit](https://github.com/vendure-ecommerce/storefront-qwik-starter/commit/9a4e601e61cde14c85134afe42055c9898f0471f) 🎉
