### ISSUE TITLE
TypeError: method.toUppercase is not a function

### ISSUE THREAD

**Issue by Frazic** [vendure-ecommerce/storefront-qwik-starter#55]
An update must have broken something because the website no longer works, it only displays this error message

`TypeError: method.toUppercase is not a function`

**Comment by michaelbromley** [comment]
Hi,
Can you include a screenshot or other instructions to reproduce? It seems to work for me.

**Comment by michaelbromley** [comment]
Oh just noticed that @gioboa made a change yesterday and then [reverted it](https://github.com/vendure-ecommerce/storefront-qwik-starter/commit/b84ecbe1f54d6a2226546ff0c93d61dd9feca728) 3 hours ago.  I'm guessing it was that?

**Comment by Frazic** [comment]
It works for me now so that must have been it!

**Comment by gioboa** [comment]
I updated all the dependencies with the latest versions and locality it works but in cloudflare something is not working as aspect. So I reverted my commit 😅
