### ISSUE TITLE
Use env variables 

### ISSUE THREAD

**Issue by gioboa** [vendure-ecommerce/storefront-qwik-starter#58]
To be customisable we need to use env variables
These are some variables:
- vendure_public_url
- homepage image
- show_reviews
- ecommerce_name

**Comment by gioboa** [comment]
Closed with [this commit](https://github.com/vendure-ecommerce/storefront-qwik-starter/commit/0eac6d494e545896a5d5cc344a9a52392a329ff9)

**Comment by michaelbromley** [comment]
Oh nice, I saw this pattern of using Zod the other day. Cool that you integrated it!
