### ISSUE TITLE
use graphql-codegen

### ISSUE THREAD

**Issue by gioboa** [vendure-ecommerce/storefront-qwik-starter#64]
It will be awesome use graphql-codegen to generate schemas and types

**Comment by riccardo-vettore** [comment]
Hi @gioboa, I will work on this!

**Comment by gioboa** [comment]
Great. Thanks

**Comment by yasserlens** [comment]
I see graphql-codegen in the codebase and I assume it's used - is this closed?

**Comment by gioboa** [comment]
Only some parts are with gql-codegen, @riccardo-vettore is doing a great incremental refactoring 👏

**Comment by gioboa** [comment]
#87 fixed this issue. @riccardo-vettore you rock 👏 Thanks
