### ISSUE TITLE
Better unfurling with <head> tags

### ISSUE THREAD

**Issue by tacheometry** [vendure-ecommerce/storefront-qwik-starter#68]
Currently, website unfurls (embeds) are the same for every link:
![image](https://user-images.githubusercontent.com/39647014/223856765-7ee041ef-f246-4b50-988a-eee050bd4fb9.png)

However, they could be better through personalized tags in each page's `<head>`. I can recommend this resource: https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254

**Comment by gioboa** [comment]
Thanks for your suggestions, I think can be deleted to #41
