### ISSUE TITLE
Error: must be non null

### ISSUE THREAD

**Issue by yasserlens** [vendure-ecommerce/storefront-qwik-starter#79]
Hello!

I found the following error while trying out the store, here's how you can replicate:
1) Browse to any product variant page
2) reload the page 

The error says "must be non null".

**Comment by gioboa** [comment]
Thanks for your feedback. It's a well known issue in Qwik, let's wait the resolution

**Comment by yasserlens** [comment]
Thanks for the update! Is there a link to the issue you're describing?
I'm planning to use this in prod - with errors like this I can't. Would be great to know more about the root cause so I could follow the progress for resolution. Many thanks

**Comment by gioboa** [comment]
https://github.com/BuilderIO/qwik/issues/3440 here the issue
I think you can prepare all the things to be ready for the production, soon it will be fixed

**Comment by gioboa** [comment]
I downgraded the Qwik version to 0.21.
do you have any error now?

**Comment by yasserlens** [comment]
Yes - 0.21 doesn't seem to have that issue. Thanks!

**Comment by gioboa** [comment]
I updated Qwik to the latest version and I fixed the `Error: must be non null` error

**Comment by jonathanlal** [comment]
I've updated to latest version and still have same error

```
    "@builder.io/qwik": "^0.101.0",
    "@builder.io/qwik-city": "^0.101.0",
```

**Comment by gioboa** [comment]
> I've updated to latest version and still have same error
> 
> ```
>     "@builder.io/qwik": "^0.101.0",
>     "@builder.io/qwik-city": "^0.101.0",
> ```

I changed also this https://github.com/vendure-ecommerce/storefront-qwik-starter/blob/e3e41dc031fd7839264e7cc5e83825d2fbc18185/src/components/image/Image.tsx#L204
I would like to use `useTask` but Qwik doesn't work correctly I guess
