### ISSUE TITLE
Error: Scroll to top before navigation

### ISSUE THREAD

**Issue by yasserlens** [vendure-ecommerce/storefront-qwik-starter#86]
When navigating from any page to another, the page scrolls to top THEN the new page is displayed.
This doesn't look right / feels buggy. 

I tried commenting out the window.scrollTo(0, 0); in scrollToTop() in utils/index.ts - that didn't help. Still getting this weird behaviour.

In case you want to see it clearly (in Chrome):
- Open the network tab
- Click on the top left menu that says "No throttling" and choose Fast 3G
- Monitor the page. It'll first scroll up, load more resources, then navigate to the target page

**Comment by gioboa** [comment]
I removed scrollToTop methods from the codebase anyway it's a Qwik [feature/issue](https://github.com/BuilderIO/qwik/pull/3244)

**Comment by yasserlens** [comment]
This is still an issue - it's very clear on a slow connection if you throttle the network.
