### ISSUE TITLE
password show/hide triggers page reload

### ISSUE THREAD

**Issue by prasmalla** [vendure-ecommerce/storefront-qwik-starter#98]
in my account section > change password clicking the password show/hide button triggers page reload

![Screenshot 2023-05-14 at 5 46 19 AM](https://github.com/vendure-ecommerce/storefront-qwik-starter/assets/776178/49b921b7-3679-413c-ba85-c43e9c99a470)

**Comment by msj121** [comment]
I think this is solved with pull request: https://github.com/vendure-ecommerce/storefront-qwik-starter/pull/116#issue-1806794218

Thanks for pointing this out.
