### ISSUE TITLE
Update Vendure API to v2.0.0

### ISSUE THREAD

**Issue by giovramirez** [vendure-ecommerce/storefront-qwik-starter#99]
Vendure v2 is now in beta, so we can start taking a look at the work that needs to be done.

**Remix storefront progress**
https://github.com/vendure-ecommerce/storefront-remix-starter/issues/40

**Vendure V2.0 migration**
https://github.com/vendure-ecommerce/vendure/discussions/1991

**Comment by prasmalla** [comment]
tested with beta2 needed changes to setting shipping method #100
everything else mentioned in the remix thread like stock levels, order history and currency symbols is working ✌🏽

**Comment by gioboa** [comment]
We updated the application, now we support vendure v2
